### ISSUE TITLE
Small pictures destroying quality of the following pictures

### ISSUE THREAD

**Issue by vincebhh** [robwierzbowski/jekyll-picture-tag#115]
Using the current version I run into the following problem:
1) I define a markup presets with widths: [200, 400, 600 ].
2) I use that preset on an image on an image with width 55.
3) The plugin throws a warning:
"Image is 55px wide, smaller than at least one size in the set [200, 400, 600 ]. Will not enlarge."
(This is expected and great!)
4) And now comes the problem:
The set of widths of the markup preset for all following images is changed to [55].
And thus all following images have a terrible quality, because they are all scaled down to a width of 55px.

The only workarounds I found so far are the following:
1) use the default markup preset without altering its width set.
2) delete the small image.

**Comment by rbuchberger** [comment]
Interesting! That is definitely a bug. I will look into it. Thanks for reporting it!

**Comment by vincebhh** [comment]
Thank you for caring about it!

If you need any help reproducing it or any other information, I am happy to help.

**Comment by rbuchberger** [comment]
I was able to reproduce it, and I believe that should fix it. Let me know if it doesn't work!

**Comment by vincebhh** [comment]
Works perfectly!
Thank you!
