### ISSUE TITLE
relative_url not working

### ISSUE THREAD

**Issue by norrishung** [robwierzbowski/jekyll-picture-tag#122]
Setting relative_url in the config.yml file doesn't have any effect. I can only get image sources to the absolute url.

**Comment by rbuchberger** [comment]
It appears to be working to me, can you share the relevant line in your Gemfile?

It's a relatively recent feature addition, maybe you're on an older version? Try running `bundle update`

**Comment by rbuchberger** [comment]
Since it's been a few days I'm going to close this, but feel free to re-open it if you need more help.
