### ISSUE TITLE
Generated images have -rw------- permissions

### ISSUE THREAD

**Issue by timakro** [robwierzbowski/jekyll-picture-tag#127]
Is there a reason why the group and others have no read permissions for the files?

**Comment by stuntbox** [comment]
I ran into the same issue. All images were getting assigned 0600 for permissions and can’t be served as a result. 

Not exactly sure what’s going on, but looks like a change in [something upstream](https://github.com/minimagick/minimagick/issues/312#issuecomment-131325465) from MiniMagick? Might not be the best solution, but just put in a [PR](https://github.com/robwierzbowski/jekyll-picture-tag/pull/128) that explicitly sets permissions on the images after they’re written so they are world readable. Open to suggestions. 

Also, wanted to say thank you for reviving this repo, @rbuchberger. You’re doing awesome work!

**Comment by rbuchberger** [comment]
Thanks for this! Reading the issue you linked, I your explicit solution is the way to go. If it causes problems for anyone down the line we can expose it in a setting.

If you're affected by this issue, you'll need to delete all your generated images so j-p-t rebuilds them with the correct permissions (or just set those permissions yourself with `chmod`).

You're welcome for reviving this repo! It ended up being more work than I expected, but it's been a good experience. I definitely appreciate the appreciation and the help.
