### ISSUE TITLE
Verify compatibility with Jekyll 4.0.0

### ISSUE THREAD

**Issue by rbuchberger** [robwierzbowski/jekyll-picture-tag#131]
Apparently there's a new version of jekyll coming out - 

https://jekyllrb.com/news/2019/03/18/jekyll-4-0-0-pre-alpha1-released/

Will need to try it out, with j-p-t!

**Comment by kylekirkby** [comment]
Hi @rbuchberger,

Any update on this ? Would love to use this plugin alongside Jekyll 4 :)

BR,

Kyle

**Comment by rbuchberger** [comment]
Hey! 

I don't know that it *doesn't* work. I haven't tested at all, you're welcome to do so and report back! 

I'm super busy with other projects. I feel bad that JPT is a bit neglected lately, but it will probably be another month or two becore I can put real time into it.

**Comment by kylekirkby** [comment]
Hey! Thanks for the reply! I might have time to test shortly and will report back if I get round to it :) :100:
