### ISSUE TITLE
Separate minimagick section into it's own repo, gemify all

### ISSUE THREAD

**Issue by robwierzbowski** [robwierzbowski/jekyll-picture-tag#19]
So we can gemify and pull into both JPT and Jekyll Image Tag.

**Comment by jerturowetz** [comment]
I'd be super interested in getting at your notes @robwierzbowski if you still have them lying around (Windows user struggling with minimagick)

**Comment by rbuchberger** [comment]
Hey, there's a massive update incoming (next week or two, hopefully) that may fix your issues. In the meantime, have you explicitly configured a source and destination directory in your _config.yml? 

 Rob isn't actively working on this gem anymore, he's kindly let me take over the daily stuff.

**Comment by robwierzbowski** [comment]
I no longer have those notes. Good luck to both of you!

**Comment by jerturowetz** [comment]
Hey @rbuchberger thanks for the update!

So far I've found that installing ImageMagick as an admin works to solve ruby path issues, though I don't know how reliably this addresses project replication. Until minimagick is in its own gem (and maybe even after), maybe the readme could note that jekyll-picture-tag uses minimagick which itself relies on ImageMagick being available in the system path?
