### ISSUE TITLE
Lack of media attribute on default fails W3C validation

### ISSUE THREAD

**Issue by davetgreen** [robwierzbowski/jekyll-picture-tag#57]
Hello!

The W3C validator expects a media/type attribute on every srcset, otherwise you get the following error:

> A source element that has a following sibling source element or img element with a srcset attribute must have a media attribute and/or type attribute.

It fails due to the fact that the default source doesn't accept this parameter, and therefore doesn't output the attribute.

Maybe default it to...

    media="(min-width: 0)"

Cheers,
Dave

**Comment by nhoizey** [comment]
I believe it's been fixed with 7188dd8cc00ee7088a1096daf39a44b0d0059ba0, isn't it?

**Comment by davetgreen** [comment]
@nhoizey Aye that would prevent the error!
