### ISSUE TITLE
Get path for a particular size

### ISSUE THREAD

**Issue by delucis** [robwierzbowski/jekyll-picture-tag#63]
It would be amazing if there were some built in functionality to ask for the path to a specific size of a generated image. There are various place where a `<picture>` tag doesn’t make sense (e.g. feeds, meta tags), but it seems a shame not to re-use already generated content. That’s not currently possible because the filename suffixes (WIDTHbyHEIGHT-etc) are unpredictable from outside of `{% picture %}`.

Could some kind of syntax along the lines of `{% picture [preset] [source] path/to/img.jpg %}` returning the path to the given source copy of the image work?

In any case, thanks for an already great plugin. :hand:

**Comment by stuntbox** [comment]
+1 RE some way to handle images in feeds.
