### ISSUE TITLE
Upgrade to v1.8.1 or later of fastimage

### ISSUE THREAD

**Issue by nhoizey** [robwierzbowski/jekyll-picture-tag#71]
It seems dependency to '~> 1.6.4' of fastimage is blocking upgrade to Jekyll 3 if we use the jekyll-assets plugin because it requires fastimage '~> 1.8'.

Current version of fastimage is 1.8.1: https://github.com/sdsykes/fastimage/releases

**Comment by envygeeks** [comment]
It's not just FastImage that needs to be updated, but MiniMagick will need to be updated or you won't be able to use our proxied image resizers as we only support 4+, this is stuck on 3.

**Comment by nhoizey** [comment]
Ok, so I'm doomed… :-/

**Comment by stuntbox** [comment]
It seems like this repo hasn't gotten much love for awhile, though I've spotted some furtive attempts to bring it back up to speed. I frankly haven't found anything that comes close to filling this badly-needed gap in our Jekyll site work. What else are folks using these days to fill the image-generation-plus-picture-element gap?

**Comment by nhoizey** [comment]
There's this other plugin: https://github.com/wildlyinaccurate/jekyll-responsive-image

And also, I have great hopes in Jekyll Assets future: https://github.com/jekyll/jekyll-assets/issues/172

**Comment by Boucherie** [comment]
I forked this gem, changed the pessimistic dependency to an optimistic one (~> to (>=), and linked the gemfile request the the forked repo. Can the same be done for minimagick?
