### ISSUE TITLE
Add class to picture element

### ISSUE THREAD

**Issue by sackwort** [robwierzbowski/jekyll-picture-tag#75]
Thanks for this great plugin. Is there a way to add a class or classes to the `<picture>` element?

**Comment by sjmcculloch** [comment]
You can specify the class in the presets:

default:
      attr:
        class: center-image padded-image
        itemprop: image
      source_lrg:
        media: "(min-width: 720px)"
        width: 780

**Comment by danbee** [comment]
@sjmcculloch This adds a class to the `<img>` tag though, not the containing `<picture>`

**Comment by sjmcculloch** [comment]
Oh to the picture - I would just grab the source and modify it by adding the .rb file to your _plugins directory

picture_tag = "<picture>\n"\
                      "#{source_tags}"\
                      "#{markdown_escape * 4}<img src=\"#{url}#{instance['source_default'][:generated_src]}\" #{html_attr_string}>\n"\
                      "#{markdown_escape * 2}</picture>\n"
