### ISSUE TITLE
Ruby version =2.5.0 required?

### ISSUE THREAD

**Issue by renatopanda** [robwierzbowski/jekyll-picture-tag#93]
I got an error trying to install the gems:
```
Resolving dependencies...
jekyll-picture-tag-1.0.1 requires ruby version = 2.5.0, which is incompatible
with the current version, ruby 2.5.1p57
```
Couldn't find any reference in the readme about this, Is there a reason for this and do I need to downgrade (or use rbenv) just to use the plugin?

**Comment by rbuchberger** [comment]
Fix is posted, it should work now. If it doesn't, please reopen this issue!

Sorry again, it was a bit of a stupid mistake that shouldn't have made it to the master branch.

**Comment by renatopanda** [comment]
The fix worked! Thanks!
